server:
  port: 9001

spring:
  sql:
    init:
      mode: always
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: root
    
      
  jpa:
    properties:
      hibernate:
        dilect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
